name: On Push - Release drafter

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.drafter.outputs.tag_name }}
    steps:
      - uses: release-drafter/release-drafter@v5.22.0
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
